### Home
GET http://localhost:5000/

### Obtener Productos
GET http://localhost:5000/productos
# Authorization: hola-mundo

### Obtener Producto
GET http://localhost:5000/productos/61e22188ec2d285b300bbfc3
# Authorization: hola-mundo

### Crear Producto
POST http://localhost:5000/productos
# Authorization: hola-mundo
Content-Type: application/json

{
    "nombre": "Producto B",
    "categoria": 3,
    "cantidad": 10,
    "precio": 1
}

### Modificar Producto
PUT http://localhost:5000/productos/61e21c565f2250267fd2bb53
# Authorization: hola-mundo
Content-Type: application/json

{
    "nombre": "abc",
    "cantidad": 5,
    "precio": 10,
    "categoria": 1
}

### Eliminar Producto
DELETE http://localhost:5000/productos/61e223810eb78c2155ae9c4a
# Authorization: hola-mundo


### Filtrar Productos
GET http://localhost:5000/productos?filter=abc
# Authorization: hola-mundo